api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    enable_swagger: true
    enable_swagger_ui: false
    formats:
        json:
            mime_types: ['application/json']

        jsonld:
            mime_types: ['application/ld+json']

        html:
            mime_types: ['text/html']
framework:
    serializer: { enable_annotations: true }
